### ISSUE TITLE
Support for context.Context

### ISSUE THREAD

**Issue by mspiegel** [akrylysov/algnhsa#1]
Great library! I didn't see support for passing around the context parameter? I don't mind submitting a pull request, but a heads up I can't get to it right away I have a couple of non-lambda side projects that need attention. But if you don't get to it first, I will write a PR eventually.

**Comment by dowlingw** [comment]
Absolutely, providing a `Context` with the `APIGatewayProxyRequest` available would be perfect.

**Comment by akrylysov** [comment]
@mspiegel @dowlingw thanks for your feedback, check my PR please https://github.com/akrylysov/algnhsa/pull/2

**Comment by akrylysov** [comment]
Fixed in version 0.5.
