### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by hfogelberg** [akrylysov/algnhsa#16]
Hello,

I was giving the package a try, just copy- pasting the sample code. However I got theses errors while building:

````
../../akrylysov/algnhsa/request.go:21:28: event.MultiValueQueryStringParameters undefined (type events.APIGatewayProxyRequest has no field or method MultiValueQueryStringParameters)
../../akrylysov/algnhsa/request.go:65:28: event.MultiValueHeaders undefined (type events.APIGatewayProxyRequest has no field or method MultiValueHeaders)
````

Any suggestions?

**Comment by akrylysov** [comment]
Hi! You need to update `aws-lambda-go`:

```sh
go get -u github.com/aws/aws-lambda-go/events
```

**Comment by akrylysov** [comment]
@hfogelberg can you try to create a simple application with a simple handler like:
```
func testHandler(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("test"))
}
```
does it work?

**Comment by ariasf** [comment]
> Hi! You need to update `aws-lambda-go`:
> 
> ```shell
> go get -u github.com/aws/aws-lambda-go/events
> ```

worked !
