### ISSUE TITLE
ALB support

### ISSUE THREAD

**Issue by adimarco** [akrylysov/algnhsa#18]
(tl;dr - this is an offer of a Pull Request if you want it, otherwise I'd be happy to fork or release a different library)

AWS fairly recently added support for their layer 7 Application Load Balancers as Lambda triggers, which is desirable as an alternative to API Gateway if only for cost reasons (API Gateway gets expensive at scale, especially if you're only using it to expose your Lambdas to http requests and not using the rest of its features).

The official AWs `aws-lambda-events` package contains the necessary request/response structures for [ALB target group events](https://github.com/aws/aws-lambda-go/blob/master/events/README_ALBTargetGroupEvents.md) now.  These are aggravatingly similar to the API Gateway events that `algnhsa` currently uses, but just different enough that it doesn't work out of the box.

Specifically, the way multi-value headers and query parameters are handled is different.  ALB target groups have a flag indicating whether multi-values are used, and depending on how that flag is set it expects one or the other of `Headers` and `MultiValueHeaders` to be set in the serialized response, and the ALB returns a 502 Bad Gateway if the wrong field is set.

Also obviously the `RequestContext` is completely different for an ALB target group event (AWS provides a mostly-empty `ALBTargetGroupRequestContext` for this).

 I have code that addresses all of this and adapts `algnhsa` to handle a request from either API Gateway or an ALB by examining the lambda event for a "resource" field (only set on API Gateway requests) and then handling with appropriate logic.

My question is: do you want me to submit this PR? Do you envision this library being able to handle requests from either source, and/or do you intend to continue actively maintaining it?  I'd be happy to release it separately also.

**Comment by akrylysov** [comment]
hi! ALB support would be a good addition. I'm interested in maintaining the module, please submit your pull request!

**Comment by adimarco** [comment]
Excellent.  I'll get everything buffed and polished and ready for submission as a proper PR.

**Comment by ARolek** [comment]
I'm also interested in this and happy to contribute / review the PR when it comes in.

**Comment by adimarco** [comment]
Hey - sorry, got sidetracked by some day job stuff.  I have this in a workable state.  I'll get a PR submitted for review this afternoon.

**Comment by ARolek** [comment]
@adimarco I know how that goes! I'm looking forward to seeing what you came up with.

**Comment by adimarco** [comment]
Submitted.  See #19

**Comment by akrylysov** [comment]
Another approach https://github.com/akrylysov/algnhsa/pull/20, sorry, it took longer than I expected.

**Comment by akrylysov** [comment]
Version 0.12.0 supports ALB, thanks for helping with it!
