### ISSUE TITLE
event.Path is inconsistent when using an API Gateway custom domain name

### ISSUE THREAD

**Issue by ARolek** [akrylysov/algnhsa#3]
When using a custom domain via API Gateway the `stage` is included in the `event.Path`. This is [discussed in the node.js implementation](https://github.com/awslabs/aws-serverless-express/issues/86) as well as the [java implementation](https://github.com/awslabs/aws-serverless-java-container/issues/34). There is still debate on how to best handle this, but it seems to me the value passed via event.Path should be consistent weather a custom domain is used or not. 

One way to solve this is to use the `event.PathParameters["proxy"]` value which appears to always contain just the URI of the request. 

To implement this, the code in newHTTPRequest() would need to be changed from:

```go
u := url.URL{
	Path:     event.Path,
	RawQuery: params.Encode(),
}
```

to

```go
u := url.URL{
	Path:     path.Join("/", event.PathParameters["proxy"]),
	RawQuery: params.Encode(),
}
```

Alternatively there could be a config to "stripBasePath" which would tell the `newHTTPRequest()` to use either `event.Path` or `path.Join("/", event.PathParameters["proxy"])`.

**Comment by akrylysov** [comment]
Thanks for reporting the issue, I'll think about the best way to implement this. As a workaround you can use `http.StripPrefix` right now:

```go
algnhsa.ListenAndServe(http.StripPrefix("/prod", http.DefaultServeMux), nil)
```

**Comment by ARolek** [comment]
Unfortunately I can't hard code in the stage that way.  I'm generating a JSON response based on request parameters. For example, take a look at the following two endpoints which point to the same lambda function:

- https://bpqmmr7g4k.execute-api.us-west-2.amazonaws.com/v1/capabilities
- https://osm-lambda.tegola.io/v1/capabilities

The second one uses a custom domain configured with API Gateway. With your current implementation the second request to the `/capabilities` endpoint will not match a route in the downstream router. This is because when using a custom domain the stage is included in `r.Path` so the router would need to match on the route `/v1/capabilities` rather than `/capabilities`. The value for `event.PathParameters["proxy"]` is consistent whether using a custom domain name for API gateway or not.
