### ISSUE TITLE
Lambda function handler

### ISSUE THREAD

**Issue by suntong** [akrylysov/algnhsa#34]
From [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html):

> For a .zip file archive, the code property specifies the location of the .zip file. You must also specify the **handler** and **runtime** properties. 

From [here](https://docs.aws.amazon.com/lambda/latest/dg/golang-handler.html):

> **func HandleRequest(ctx context.Context, name MyEvent) (string, error)**: This is your Lambda handler signature and includes the code which will be executed. 

This Lambda handler signature is different from the `addHandler` and/or `contextHandler` in README.

So if I use the [create-function](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html) to create  Lambda function, how should I specify its mandatory Handler parameter pls? thx.

**Comment by akrylysov** [comment]
The AWS documentation is slightly confusing. In the first paragraph `You must also specify the handler and runtime properties` _handler_ is the name of the compiled binary inside the zip file you provide.

If you build the lambda zip package using the following code:

```
GOOS=linux GOARCH=amd64 go build -o handler
zip handler.zip handler
```
then the handler name is literally _handler_.

Does this help?

**Comment by suntong** [comment]
Works like a charm. THANKS!
