### ISSUE TITLE
dev mode

### ISSUE THREAD

**Issue by nkev** [akrylysov/algnhsa#9]
Is something like this the best way to determine if running locally?

```Go
func main() {
        isAWS := os.Getenv("AWS_REGION")
	r := chi.NewRouter()
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("index"))
	})

	if isAWS == "" {
		//only if dev
		log.Println("Serving on localhost:9090")
		http.ListenAndServe(":9000", r)
	} else {
		//only if production:
		log.Println("Started Lambda function")
		algnhsa.ListenAndServe(r, nil)
	}
}
```

I got the env variable from https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by akrylysov** [comment]
Your approach should work, you can also try the `_LAMBDA_SERVER_PORT` variable which is used by the `aws-lambda-go` package (https://github.com/aws/aws-lambda-go/blob/master/lambda/entry.go#L51).

**Comment by nkev** [comment]
Thanks.
